/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__token_token1 = 1,
  sym_identifier = 2,
  sym_number = 3,
  sym_string = 4,
  anon_sym_LPAREN_STAR = 5,
  aux_sym_comment_token1 = 6,
  anon_sym_STAR = 7,
  aux_sym_comment_token2 = 8,
  anon_sym_STAR_RPAREN = 9,
  sym_source_file = 10,
  sym__token = 11,
  sym_comment = 12,
  aux_sym_source_file_repeat1 = 13,
  aux_sym_comment_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__token_token1] = "_token_token1",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_LPAREN_STAR] = "(*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_STAR] = "*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_STAR_RPAREN] = "*)",
  [sym_source_file] = "source_file",
  [sym__token] = "_token",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__token_token1] = aux_sym__token_token1,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_LPAREN_STAR] = anon_sym_LPAREN_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_STAR_RPAREN] = anon_sym_STAR_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym__token] = sym__token,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__token_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 6,
  [10] = 7,
  [11] = 6,
  [12] = 7,
  [13] = 13,
  [14] = 4,
  [15] = 5,
  [16] = 16,
  [17] = 17,
  [18] = 4,
  [19] = 5,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == '*') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == '*') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(15);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '(') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym__token_token1);
      if (lookahead == '"') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__token_token1);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(11);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__token_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__token_token1);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__token_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(11);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(15);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == ')') ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '(') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(15);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_STAR_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 3},
  [18] = {(TSStateId)(-1),},
  [19] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LPAREN_STAR] = ACTIONS(3),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_STAR_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(16),
    [sym__token] = STATE(2),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym__token_token1] = ACTIONS(7),
    [sym_identifier] = ACTIONS(7),
    [sym_number] = ACTIONS(7),
    [sym_string] = ACTIONS(7),
    [anon_sym_LPAREN_STAR] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__token] = STATE(3),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [aux_sym__token_token1] = ACTIONS(13),
    [sym_identifier] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [anon_sym_LPAREN_STAR] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym__token] = STATE(3),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [aux_sym__token_token1] = ACTIONS(17),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN_STAR] = ACTIONS(20),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_comment,
    ACTIONS(25), 5,
      aux_sym__token_token1,
      sym_identifier,
      sym_number,
      sym_string,
      anon_sym_LPAREN_STAR,
  [14] = 3,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_comment,
    ACTIONS(29), 5,
      aux_sym__token_token1,
      sym_identifier,
      sym_number,
      sym_string,
      anon_sym_LPAREN_STAR,
  [28] = 6,
    ACTIONS(31), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(33), 1,
      aux_sym_comment_token1,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_STAR_RPAREN,
    STATE(6), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_comment_repeat1,
  [47] = 6,
    ACTIONS(31), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(39), 1,
      aux_sym_comment_token1,
    ACTIONS(41), 1,
      anon_sym_STAR_RPAREN,
    STATE(7), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_comment_repeat1,
  [66] = 5,
    ACTIONS(43), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(46), 1,
      aux_sym_comment_token1,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(52), 1,
      anon_sym_STAR_RPAREN,
    STATE(8), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [83] = 6,
    ACTIONS(31), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(54), 1,
      aux_sym_comment_token1,
    ACTIONS(56), 1,
      anon_sym_STAR_RPAREN,
    STATE(9), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_comment_repeat1,
  [102] = 6,
    ACTIONS(31), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(39), 1,
      aux_sym_comment_token1,
    ACTIONS(58), 1,
      anon_sym_STAR_RPAREN,
    STATE(8), 1,
      aux_sym_comment_repeat1,
    STATE(10), 1,
      sym_comment,
  [121] = 6,
    ACTIONS(31), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(60), 1,
      aux_sym_comment_token1,
    ACTIONS(62), 1,
      anon_sym_STAR_RPAREN,
    STATE(11), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_comment_repeat1,
  [140] = 6,
    ACTIONS(31), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(39), 1,
      aux_sym_comment_token1,
    ACTIONS(64), 1,
      anon_sym_STAR_RPAREN,
    STATE(8), 1,
      aux_sym_comment_repeat1,
    STATE(12), 1,
      sym_comment,
  [159] = 2,
    STATE(13), 1,
      sym_comment,
    ACTIONS(52), 4,
      anon_sym_LPAREN_STAR,
      aux_sym_comment_token1,
      anon_sym_STAR,
      anon_sym_STAR_RPAREN,
  [169] = 2,
    STATE(14), 1,
      sym_comment,
    ACTIONS(25), 4,
      anon_sym_LPAREN_STAR,
      aux_sym_comment_token1,
      anon_sym_STAR,
      anon_sym_STAR_RPAREN,
  [179] = 2,
    STATE(15), 1,
      sym_comment,
    ACTIONS(29), 4,
      anon_sym_LPAREN_STAR,
      aux_sym_comment_token1,
      anon_sym_STAR,
      anon_sym_STAR_RPAREN,
  [189] = 3,
    ACTIONS(3), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym_comment,
  [199] = 3,
    ACTIONS(68), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(70), 1,
      aux_sym_comment_token2,
    STATE(17), 1,
      sym_comment,
  [209] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [213] = 1,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 14,
  [SMALL_STATE(6)] = 28,
  [SMALL_STATE(7)] = 47,
  [SMALL_STATE(8)] = 66,
  [SMALL_STATE(9)] = 83,
  [SMALL_STATE(10)] = 102,
  [SMALL_STATE(11)] = 121,
  [SMALL_STATE(12)] = 140,
  [SMALL_STATE(13)] = 159,
  [SMALL_STATE(14)] = 169,
  [SMALL_STATE(15)] = 179,
  [SMALL_STATE(16)] = 189,
  [SMALL_STATE(17)] = 199,
  [SMALL_STATE(18)] = 209,
  [SMALL_STATE(19)] = 213,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [66] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_coq(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "coq",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
